# Pipeline parameters
pipeline_project: !!str DeepCORO_video_linear_probing
output_dir: !!str outputs
run_mode: !!str train
epochs: !!int 10
seed: !!int 42
# wandb parameters
tag: !!str mvit_pretrained
name: !!str DeepCORO_video_linear_probing_cathEF
project: !!str DeepCORO_video_linear_probing_cathEF
entity: !!str mhi_ai
use_wandb: !!bool true
# Training parameters
lr: !!float 0.001
scheduler_name: !!str step
lr_step_period: !!int 5
factor: !!float 0.3
optimizer: !!str AdamW
weight_decay: !!float 0.00001
use_amp: !!bool true
gradient_accumulation_steps: !!int 1
num_warmup_percent: !!float 0.1
num_hard_restarts_cycles: !!float 1.0
warm_restart_tmult: !!int 2
# Dataset parameters
data_filename: !!str data/CathEF_MHI_UCSF_2016-to-july-2022-and-2023-08-30-post-CathEF_alpha_filtered.csv
num_workers: !!int 32
batch_size: !!int 16
datapoint_loc_label: !!str FileName
target_label: [Value]
rand_augment: !!bool true
resize: !!int 224
frames: !!int 16
stride: !!int 1
# Video Encoder parameters
model_name: !!str mvit
aggregator_depth: !!int 2
num_heads: !!int 4
video_freeze_ratio: !!float 0.8
dropout: !!float 0.2
pretrained: !!bool true
video_encoder_lr: !!float 1e-5
video_encoder_checkpoint_path: !!str outputs/dev_deep_coro_clip_single_video/mvit_pretrained_mvit_b24_f16_AdamW_lr2.527361715636149e-05_20250325-001727_xvwwv5ar/checkpoints/best_epoch.pt
# Linear Probing parameters
linear_probing_head: !!str simple_linear_probing_regression
head_structure: # output dimension of each head
  Value: !!int 1
head_dropout: # dropout for each head
  Value: !!float 0.1
loss_structure: # loss function for each head
  Value: !!str mse
head_weights: # weight for each head
  Value: !!float 1.0
head_task: # task for each head
  Value: !!str regression
# Label mappings - Used for confusion matrix
labels_map: # label mapping for each head
  Value:
    Value: !!str regression
