# Pipeline parameters
pipeline_project: !!str DeepCORO_video_linear_probing
base_checkpoint_path: !!str outputs
run_mode: !!str train
epochs: !!int 15
seed: !!int 42
# wandb parameters
name: !!str DeepCORO_video_linear_probing_cathEF
project: !!str DeepCORO_video_linear_probing_cathEF
entity: !!str mhi_ai
use_wandb: !!bool true
# Training parameters
scheduler_name: !!str step
lr_step_period: !!int 5
factor: !!float 0.3
optimizer: !!str AdamW
use_amp: !!bool true
gradient_accumulation_steps: !!int 1
num_warmup_percent: !!float 0.1
num_hard_restarts_cycles: !!float 1.0
warm_restart_tmult: !!int 2
# Dataset parameters
data_filename: !!str data/reports/CathEF_MHI_UCSF_2016-to-july-2022-and-2023-08-30-post-CathEF_alpha_StudyInstanceUID_updated.csv
num_workers: !!int 24
batch_size: !!int 24
multi_video: !!bool true
groupby_column: !!str 'StudyInstanceUID'
num_videos: !!int 4
pooling_mode: !!str attention
shuffle_videos: !!bool true
datapoint_loc_label: !!str FileName
target_label: [Value, y_true_cat]
rand_augment: !!bool true
resize: !!int 224
frames: !!int 32
stride: !!int 1
# Video Encoder parameters
model_name: !!str x3d_m
aggregator_depth: !!int 2
num_heads: !!int 4
video_freeze_ratio: !!float 0.8
dropout: !!float 0.2
pretrained: !!bool true
video_encoder_lr: !!float 1e-5
video_encoder_checkpoint_path: !!str outputs/checkpoints/DeepCORO_clip/DeepCORO_Clip_Sweep_Multi_Video/cvlag76n_20250511-204014/outputs/checkpoints/DeepCORO_clip/DeepCORO_Clip_Sweep_Multi_Video/cvlag76n_20250511-204547/checkpoints/best_model_epoch_24.pt
video_encoder_weight_decay: !!float 0.00000387825282805052
attention_lr: !!float 1e-4
attention_weight_decay: !!float 0.0
output_dir: !!str outputs/
# Linear Probing parameters
head_linear_probing: # linear probing class for each head
  Value: !!str simple_linear_probing_regression
  y_true_cat: !!str simple_linear_probing
head_structure: # output dimension of each head
  Value: !!int 1
  y_true_cat: !!int 1
head_dropout: # dropout for each head
  Value: !!float 0.1
  y_true_cat: !!float 0.1
loss_structure: # loss function for each head
  Value: !!str mae
  y_true_cat: !!str bce_logit
head_lr: # learning rate for each head
  Value: !!float 0.00006998050654973559
  y_true_cat: !!float 0.00006998050654973559
head_weight_decay: # weight decay for each head
  Value: !!float 0.00000387825282805052
  y_true_cat: !!float 0.00000387825282805052
head_weights: # weight per head for loss computation - f_loss = f_loss * f_weight + f_loss_2 * f_weight_2 + ...
  Value: !!float 1.0
  y_true_cat: !!float 1.0
head_task: # task for each head
  Value: !!str regression
  y_true_cat: !!str classification
# Label mappings - Used for confusion matrix
labels_map: # label mapping for each head
  Value:
    Value: !!str regression
  y_true_cat:
    y_true_cat: !!str EF
