# Dataset Generation Configuration Template
# This file contains all available configuration options for generate_dataset.py

# Filter settings for data preprocessing
filters:
  # Status filter - can be a single status or a list of statuses
  # Single status example:
  # status: "diagnostic"
  # Multiple statuses example:
  status: 
    - "diagnostic"
  #  - "POST_PCI"
  # Available values: "diagnostic", "PCI", "POST_PCI"
  
  # Main structures to include in the dataset
  main_structures:
    - "Left Coronary"
    - "Right Coronary"
  
  # Contrast agent class filter (1 = positive, 0 = negative)
  contrast_agent_class: 1

# Report generation settings
report_settings:
  # Whether to generate coronary-specific reports (True/False)
  # If True, reports will be tailored to the specific coronary side
  # If False, comprehensive reports will be generated for all vessels
  coronary_specific: true

# Train/test split settings
train_test_split:
  # Whether to enable train/val/test split (True/False)
  enabled: true
  
  # Ratio of patients for training set (0.0-1.0)
  train_ratio: 0.7
  
  # Ratio of patients for validation set (0.0-1.0)
  val_ratio: 0.1
  
  # Ratio of patients for test set (0.0-1.0, will be computed as 1 - train_ratio - val_ratio if not specified)
  test_ratio: 0.2
  
  # Random seed for reproducible splits
  random_state: 42
  
  # Column containing patient IDs for patient-based splitting
  patient_column: "CathReport_MRN"
  
  # Whether to save separate files for each split
  save_separate_files: false

# Sampling settings for creating balanced datasets
sampling:
  # Whether to enable sampling (True/False)
  enabled: true
  
  # Number of samples to take per group
  n_per_group: 9
  
  # Column to group by for sampling
  label_column: "status"

# Data mapping settings
# Whether to apply predefined mappings to categorical variables
apply_mappings: true

# Whether to auto-assign status based on PCI timing
assign_status: true

# Output settings
output_settings:
  # Separator character for CSV files (use "α" for alpha separator)
  separator: "α"
  
  # Whether to include index column in output
  include_index: false

# Optional: Custom mappings (if different from defaults)
# custom_mappings:
#   main_structure_map:
#     0: "Left Coronary"
#     1: "Right Coronary"
#     # ... additional mappings
#   
#   dominance_map:
#     0: "right_dominant"
#     1: "left_dominant"

# Optional: Additional processing settings
# processing:
#   # Remove rows with missing critical data
#   remove_missing_critical: true
#   
#   # Critical columns that must have values
#   critical_columns:
#     - "FileName"
#     - "main_structure_name"
#     - "status"
#   
#   # Validation settings
#   validate_reports: true 