coverage:
  status:
    project:
      default:
        target: 80%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target
    patch:
      default:
        target: 80%
        threshold: 1%

ignore:
  - "tests/**/*"       # ignore test files
  - "setup.py"         # ignore setup.py
  - "**/__init__.py"   # ignore init files
  - "scripts/**/*"     # ignore scripts directory 