# Pipeline parameters
pipeline_project: !!str DeepCORO_Multiview
output_dir: !!str outputs
run_mode: !!str train
epochs: !!int 5
seed: !!int 42
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
num_videos: 3
root: "/volume/DeepCORO_CLIP_Sarra" # adapte selon ton arborescence
input_channels: 3
num_frames: 16
# wandb parameters
tag: !!str mvit_pretrained
name: !!str dev_deep_coro_linear_probing
project: !!str dev_deep_coro_linear_probing
entity: !!str mhi_ai
use_wandb: !!bool true
# Training parameters
lr: !!float 0.01
scheduler_name: !!str step
lr_step_period: !!int 5
factor: !!float 0.3
optimizer: !!str AdamW
weight_decay: !!float 0.00001
use_amp: !!bool false
gradient_accumulation_steps: !!int 1
num_warmup_percent: !!float 0.1
num_hard_restarts_cycles: !!float 1.0
warm_restart_tmult: !!int 2
# Dataset parameters
data_filename: !!str /volume/DeepCORO_CLIP_Sarra/data/dr_rca_no_major_class.csv
num_workers: !!int 8
batch_size: !!int 4
datapoint_loc_label: !!str FileName
target_label: [prox_rca_stenosis_binary, mid_rca_stenosis_binary, dist_rca_stenosis_binary, pda_stenosis_binary, posterolateral_stenosis_binary]
rand_augment: !!bool true
resize: !!int 224
frames: !!int 16
stride: !!int 1
object_value_filter: !!int 9 #all
embeddings_dir: !!str /volume/DeepCORO_CLIP_Sarra/dataembd/video_embeddings/xvwwv5ar
# Video Encoder parameters
model_name: !!str mvit
aggregator_depth: !!int 2
num_heads: !!int 4
video_freeze_ratio: !!float 0.8
dropout: !!float 0.2
pretrained: !!bool true
video_encoder_lr: !!float 1e-5
video_encoder_checkpoint_path: !!str /volume/DeepCORO_CLIP_Sarra/data/best_epoch/best_epoch_xvwwv5ar.pt
# Linear Probing parameters
task: !!str classification
linear_probing_head: !!str simple_linear_probing
head_structure:
  prox_rca_stenosis_binary: !!int 1 # Update head structure for proximal RCA stenosis
  mid_rca_stenosis_binary: !!int 1 # Update head structure for mid RCA stenosis
  dist_rca_stenosis_binary: !!int 1 # Update head structure for distal RCA stenosis
  pda_stenosis_binary: !!int 1 # Update head structure for PDA stenosis
  posterolateral_stenosis_binary: !!int 1 # Update head structure for posterolateral stenosis
head_dropout:
  prox_rca_stenosis_binary: !!float 0.1 # Vous pouvez ajuster si besoin
  mid_rca_stenosis_binary: !!float 0.1 # Vous pouvez ajuster si besoin
  dist_rca_stenosis_binary: !!float 0.1 # Vous pouvez ajuster si besoin
  pda_stenosis_binary: !!float 0.1 # Vous pouvez ajuster si besoin
  posterolateral_stenosis_binary: !!float 0.1 # Vous pouvez ajuster si besoin
loss_structure:
  prox_rca_stenosis_binary: !!str bce_logit # Update loss function for proximal RCA stenosis
  mid_rca_stenosis_binary: !!str bce_logit # Update loss function for mid RCA stenosis
  dist_rca_stenosis_binary: !!str bce_logit # Update loss function for distal RCA stenosis
  pda_stenosis_binary: !!str bce_logit # Update loss function for PDA stenosis
  posterolateral_stenosis_binary: !!str bce_logit # Update loss function for posterolateral stenosis
head_weights:
  prox_rca_stenosis_binary: !!float 1.0
  mid_rca_stenosis_binary: !!float 1.0
  dist_rca_stenosis_binary: !!float 1.0
  pda_stenosis_binary: !!float 1.0
  posterolateral_stenosis_binary: !!float 1.0
labels_map:
  prox_rca_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1 # Update labels for proximal RCA stenosis
  mid_rca_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1 # Update labels for mid RCA stenosis
  dist_rca_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1 # Update labels for distal RCA stenosis
  pda_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1 # Update labels for PDA stenosis
  posterolateral_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1 # Update labels for posterolateral stenosis# Label mappings - Used for confusion matri
