pipeline_project: !!str "DeepCORO_clip"
base_checkpoint_path: !!str outputs
# Training parameters
epochs: !!int 20
num_workers: !!int 12
debug: !!bool false
use_amp: !!bool true
period: !!int 1
run_mode: !!str train
# Dataset parameters
data_filename: !!str data/reports/reports_with_alpha_separator_with_Calcifc_Stenosis_IFR_20250507_STUDYLEVEL.csv
root: !!str "."
target_label: !!str Report
datapoint_loc_label: !!str FileName
frames: !!int 64
stride: !!int 1
multi_video: !!bool true
num_videos: !!int 3
groupby_column: !!str StudyInstanceUID
shuffle_videos: !!bool true
batch_size: !!int 24
# Seed
seed: !!int 42
# Model parameters
model_name: !!str x3d_m
pretrained: !!bool true
# Optimizer parameters
optimizer: !!str RAdam
scheduler_name: !!str cosine
lr: !!float 0.00017282363443966767
lr_step_period: !!int 15
factor: !!float 0.22746441837088
loss_name: !!str siglip_ddp
video_weight_decay: !!float 3.142419833943754e-7
text_weight_decay: !!float 9.471043651844774e-7
gradient_accumulation_steps: !!int 1
num_warmup_percent: !!float 0.1
num_hard_restarts_cycles: !!float 1.0
warm_restart_tmult: !!int 2
max_grad_norm: !!float 1.0
# Model architecture parameters
num_heads: !!int 4
aggregator_depth: !!int 1
temperature: !!float 0.0602456055040935
dropout: !!float 0.18399459572197663
video_freeze_ratio: !!float 0.8603312444481843
text_freeze_ratio: !!float 0.8516649881704339
# Checkpointing
resume_training: !!bool false
checkpoint: !!str outputs/deepCORO_CLIP/DeepCORO_Clip_Sweep_Learnable_Temp_Full_mvit_b12_f16_RAdam_lr0.0001_20250114-190320_2o5xoevj/checkpoints/latest.pt
output_dir: !!str outputs
save_best: !!str loss
# Metrics
# Recall @k
recall_k: [1, 5, 10, 50]
# NDCG @k
ndcg_k: [5]
# Data augmentation
rand_augment: !!bool true
resize: !!int 224
apply_mask: !!bool false
# wandb parameters
tag: !!str mvit_pretrained
name: !!str dev_deep_coro_clip_single_video
project: !!str dev_deep_coro_clip_single_video
entity: !!str mhi_ai
use_wandb: !!bool true
# Inference parameters
topk: !!int 5
text_embeddings_path: !!str /media/data1/datasets/ECG_Tokenizer/utils/inference/reports_embeddings.pt
metadata_path: !!str /media/data1/datasets/ECG_Tokenizer/utils/inference/reports_metadata.parquet
inference_results_path: !!str checkpoints/inference/
