command:
  - torchrun
  - "--nproc_per_node=2"
  - "--master_port=29500"
  - "--nnodes=1"
  - "--node_rank=0"
  - "scripts/train_model_multi_gpu.py"
  - "--config"
  - "config/default_config.yaml"
name: "My_DeepCORO_Clip_Sweep"
project: "deepcoro_clip"
entity: "jacques-delfrate"
method: "bayes"
metric:
  name: "val/loss"
  goal: "minimize"
parameters:
  lr:
    min: 1e-8
    max: 2e-5
    distribution: "uniform"
  optimizer:
    values: ["AdamW"]
  scheduler_type:
    values: ["cosine"]
  lr_step_period:
    values: [1, 5, 10]
  factor:
    values: [0.1, 0.3, 0.5]
  batch_size:
    values: [8, 16, 32]
  temperature:
    min: 0.01
    max: 2.0
    distribution: uniform
early_terminate:
  type: hyperband
  min_iter: 3
  eta: 2
  s: 2
