name: 'DeepCORO_Multitask_Sweep_Fixed'
project: 'DeepCORO_Multitask'
entity: 'mhi_ai'
method: bayes
metric:
  goal: minimize
  name: val/loss

parameters:
  # Learning rates for different components
  lr:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.0001
  
  text_lr:
    distribution: log_uniform_values
    min: 0.000005
    max: 0.00005
  
  captioning_lr:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.0001
  
  mvm_lr:
    distribution: log_uniform_values
    min: 0.000001
    max: 0.00001
  
  # Weight decay parameters
  video_weight_decay:
    distribution: log_uniform_values
    min: 0.000001
    max: 0.0001
  
  text_weight_decay:
    distribution: log_uniform_values
    min: 0.0000001
    max: 0.00001
  
  # Model architecture parameters
  temperature:
    distribution: log_uniform_values
    min: 0.01
    max: 0.1
  
  dropout:
    distribution: uniform
    min: 0.1
    max: 0.3
  
  video_freeze_ratio:
    distribution: uniform
    min: 0.5
    max: 0.9
  
  text_freeze_ratio:
    distribution: uniform
    min: 0.5
    max: 0.9
  
  # Training parameters - keep batch size fixed for stability
  batch_size:
    value: 8
  
  gradient_accumulation_steps:
    values: [1, 2]
  
  # Optimizer parameters
  num_warmup_percent:
    distribution: uniform
    min: 0.05
    max: 0.15
  
  max_grad_norm:
    values: [1.0, 2.0]

command:
  - python
  - -m
  - torch.distributed.run
  - --nproc_per_node=4
  - --master_port=0
  - --nnodes=1
  - --node_rank=0
  - scripts/main.py
  - --base_config
  - "config/clip/multitask_config.yaml"