command:
  - torchrun
  - "--nproc_per_node=2"
  - "--master_port=29500"
  - "scripts/main.py"
  - "--base_config"
  - "config/clip/base_config.yaml"
  - ${args}

name: "dev_deep_coro_clip_single_video"
project: "dev_deep_coro_clip_single_video"
entity: "mhi_ai"

method: bayes

metric:
  name: best_val_loss
  goal: minimize

parameters:
  lr:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.0001

  optimizer:
    values: ["RAdam", "AdamW"]

  scheduler_name:
    values: ["linear_warmup", "cosine_with_warmup", "cosine_with_hard_restarts_with_warmup"]

  lr_step_period:
    values: [15, 20, 30]

  gradient_accumulation_steps:  
    values: [1]

  num_warmup_percent:
    values: [0.05, 0.1, 0.15]

  factor:
    distribution: uniform
    min: 0.10
    max: 0.30
    
  stride:
    values: [1, 2, 3]
    
  batch_size:
    values: [64, 96]

  aggregate_videos_tokens:
    values: [true, false]

  dropout:
    distribution: uniform
    min: 0.1
    max: 0.2

  video_freeze_ratio:
    distribution: uniform
    min: 0.0
    max: 0.15
  
  multi_video:
    values: [false]

  text_freeze_ratio:
    distribution: uniform
    min: 0.7
    max: 0.95

  num_heads:
    values: [2, 4, 8, 16]

  aggregator_depth:
    values: [1, 2, 4]

  temperature:
    distribution: uniform
    min: 0.05
    max: 0.1

  video_weight_decay:
    distribution: log_uniform_values
    min: 1e-7
    max: 1e-4
  text_weight_decay:
    distribution: log_uniform_values
    min: 1e-7
    max: 1e-6

  loss_name:  
    values: ["siglip_ddp"]

  name:
    values: ["dev_deep_coro_clip_single_video"]
  project:
    values: ["dev_deep_coro_clip_single_video"]
  entity:
    values: ["mhi_ai"]

early_terminate:
  type: hyperband
  min_iter: 3
  eta: 2
  s: 2
