command:
  - torchrun
  - "--nproc_per_node=4"
  - "--master_port=29500"
  - "scripts/main.py"
  - "--base_config"
  - "config/linear_probing/base_config_CathEF.yaml"
  - ${args}
name: "DeepCORO_video_linear_probing_cathEF"
project: "DeepCORO_video_linear_probing_cathEF"
entity: "mhi_ai"
method: bayes
metric:
  name: best_val_loss
  goal: minimize
parameters:
  lr:
    distribution: uniform
    min: 0.0001
    max: 0.001
  optimizer:
    values: [RAdam, AdamW]
  scheduler_name:
    values: ["linear_warmup", "cosine_with_warmup", "cosine_with_hard_restarts_with_warmup"]
  num_warmup_percent:
    values: [0.1, 0.15, 0.2]
  lr_step_period:
    values: [1, 2, 3]
  factor:
    distribution: uniform
    min: 0.2
    max: 0.5
  stride:
    values: [1, 2]
  dropout:
    distribution: uniform
    min: 0.1
    max: 0.5
  video_freeze_ratio:
    distribution: uniform
    min: 0.7
    max: 1.0
  weight_decay: 
    distribution: uniform
    min: 1e-7
    max: 1e-6
  batch_size:
    values: [8, 16, 24, 32, 64]
  tag:
    values: ["mvit_pretrained"]
  name:
    values: ["DeepCORO_video_linear_probing_cathEF"]
  project:
    values: ["DeepCORO_video_linear_probing_cathEF"]
  entity:
    values: ["mhi_ai"]
early_terminate:
  type: hyperband
  min_iter: 3
  eta: 2
  s: 2
run_mode: train