# Pipeline parameters
pipeline_project: !!str DeepCORO_video_linear_probing
#output_dir: !!str outputs
base_checkpoint_path: !!str outputs
run_mode: !!str train
epochs: !!int 15
seed: !!int 42
# wandb parameters
tag: !!str mvit_pretrained
name: !!str mil_probing_2vue
project: !!str DeepCORO-MIL
entity: !!str mhi_ai
use_wandb: !!bool true
# Training parameters
#lr: !!float 0.0003
scheduler_name: !!str cosine_with_warmup
lr_step_period: !!int 5
factor: !!float 0.3
optimizer: !!str AdamW
#weight_decay: !!float 0.00001
use_amp: !!bool true
gradient_accumulation_steps: !!int 1
num_warmup_percent: !!float 0.1
num_hard_restarts_cycles: !!float 1.0
warm_restart_tmult: !!int 1
# Dataset parameters
data_filename: !!str /volume/Deep_CORO_Multi_Instance/data/data_equilibree.csv
num_workers: !!int 8
batch_size: !!int 4
multi_video: !!bool true
groupby_column: !!str 'StudyInstanceUID'
num_videos: !!int 4
pooling_mode: !!str attention
attention_hidden: 256 # Hidden dim for attention mechanism
dropout_attention: 0.1 # Dropout within attention block
shuffle_videos: !!bool true
datapoint_loc_label: !!str FileName
target_label: [leftmain_stenosis_binary, lad_stenosis_binary, mid_lad_stenosis_binary, dist_lad_stenosis_binary, diagonal_stenosis_binary, D2_stenosis_binary, lcx_stenosis_binary, dist_lcx_stenosis_binary, om1_stenosis_binary, om2_stenosis_binary, bx_stenosis_binary, leftmain_stenosis, lad_stenosis, mid_lad_stenosis, dist_lad_stenosis, diagonal_stenosis, D2_stenosis, lcx_stenosis, dist_lcx_stenosis, om1_stenosis, om2_stenosis, bx_stenosis, prox_rca_stenosis_binary, mid_rca_stenosis_binary, dist_rca_stenosis_binary, pda_stenosis_binary, posterolateral_stenosis_binary, prox_rca_stenosis, mid_rca_stenosis, dist_rca_stenosis, pda_stenosis, posterolateral_stenosis]
rand_augment: !!bool true
resize: !!int 224
frames: !!int 32
stride: !!int 1
per_video_pool: !!bool false
# Video Encoder parameters
model_name: !!str mvit
aggregator_depth: !!int 2
num_heads: !!int 4
video_freeze_ratio: !!float 0.8
dropout: !!float 0.2
pretrained: !!bool true
video_encoder_lr: !!float 1e-5
video_encoder_checkpoint_path: !!str /volume/Deep_CORO_Multi_Instance/data/checkpoint/check/highest_alignment_epoch_24.pt
video_encoder_weight_decay: !!float 0.00000387825282805052
attention_lr: !!float 1e-4
attention_weight_decay: !!float 0.0
output_dir: !!str outputs/
# Linear Probing parameters
task: !!str classification
head_linear_probing: # linear probing class for each head
  leftmain_stenosis: !!str simple_linear_probing_regression
  leftmain_stenosis_binary: !!str simple_linear_probing
  lad_stenosis: !!str simple_linear_probing_regression
  lad_stenosis_binary: !!str simple_linear_probing
  mid_lad_stenosis: !!str simple_linear_probing_regression
  mid_lad_stenosis_binary: !!str simple_linear_probing
  dist_lad_stenosis: !!str simple_linear_probing_regression
  dist_lad_stenosis_binary: !!str simple_linear_probing
  diagonal_stenosis: !!str simple_linear_probing_regression
  diagonal_stenosis_binary: !!str simple_linear_probing
  D2_stenosis: !!str simple_linear_probing_regression
  D2_stenosis_binary: !!str simple_linear_probing
  lcx_stenosis: !!str simple_linear_probing_regression
  lcx_stenosis_binary: !!str simple_linear_probing
  dist_lcx_stenosis: !!str simple_linear_probing_regression
  dist_lcx_stenosis_binary: !!str simple_linear_probing
  om1_stenosis: !!str simple_linear_probing_regression
  om1_stenosis_binary: !!str simple_linear_probing
  om2_stenosis: !!str simple_linear_probing_regression
  om2_stenosis_binary: !!str simple_linear_probing
  bx_stenosis: !!str simple_linear_probing_regression
  bx_stenosis_binary: !!str simple_linear_probing
  rox_rca_stenosis: !!str simple_linear_probing_regression
  prox_rca_stenosis_binary: !!str simple_linear_probing
  mid_rca_stenosis: !!str simple_linear_probing_regression
  mid_rca_stenosis_binary: !!str simple_linear_probing
  dist_rca_stenosis: !!str simple_linear_probing_regression
  dist_rca_stenosis_binary: !!str simple_linear_probing
  pda_stenosis: !!str simple_linear_probing_regression
  pda_stenosis_binary: !!str simple_linear_probing
  posterolateral_stenosis: !!str simple_linear_probing_regression
  posterolateral_stenosis_binary: !!str simple_linear_probing
head_structure:
  leftmain_stenosis_binary: !!int 1 # Update head structure for leftmain stenosis
  lad_stenosis_binary: !!int 1 # Update head structure for lad stenosis
  mid_lad_stenosis_binary: !!int 1 # Update head structure for mid lad stenosis
  dist_lad_stenosis_binary: !!int 1 # Update head structure for dist lad stenosis
  diagonal_stenosis_binary: !!int 1 # Update head structure for diagonal stenosis
  D2_stenosis_binary: !!int 1 # Update head structure for D2 stenosis
  lcx_stenosis_binary: !!int 1 # Update head structure for lcx stenosis
  dist_lcx_stenosis_binary: !!int 1 # Update head structure for dist lcx stenosis
  om1_stenosis_binary: !!int 1 # Update head structure for om1 stenosis
  om2_stenosis_binary: !!int 1 # Update head structure for om2 stenosis
  bx_stenosis_binary: !!int 1 # Update head structure for bx stenosis
  leftmain_stenosis_binary: !!int 1 # Update head structure for leftmain stenosis
  lad_stenosis: !!int 1 # Update head structure for lad stenosis
  mid_lad_stenosis: !!int 1 # Update head structure for mid lad stenosis
  dist_lad_stenosis: !!int 1 # Update head structure for dist lad stenosis
  diagonal_stenosis: !!int 1 # Update head structure for diagonal stenosis
  D2_stenosis: !!int 1 # Update head structure for D2 stenosis
  lcx_stenosis: !!int 1 # Update head structure for lcx stenosis
  dist_lcx_stenosis: !!int 1 # Update head structure for dist lcx stenosis
  om1_stenosis: !!int 1 # Update head structure for om1 stenosis
  om2_stenosis: !!int 1 # Update head structure for om2 stenosis
  bx_stenosis: !!int 1 # Update head structure for bx stenosis
  prox_rca_stenosis_binary: !!int 1 # Binary classification for proximal RCA stenosis
  mid_rca_stenosis_binary: !!int 1 # Binary classification for mid RCA stenosis
  dist_rca_stenosis_binary: !!int 1 # Binary classification for distal RCA stenosis
  pda_stenosis_binary: !!int 1 # Binary classification for PDA stenosis
  posterolateral_stenosis_binary: !!int 1 # Binary classification for posterolateral stenosis
  prox_rca_stenosis: !!int 1 #  regression for proximal RCA stenosis
  mid_rca_stenosis: !!int 1 # regression for mid RCA stenosis
  dist_rca_stenosis: !!int 1 #  regression for distal RCA stenosis
  pda_stenosis: !!int 1 #  regression for PDA stenosis
  posterolateral_stenosis: !!int 1 # regression for posterolateral stenosis
head_dropout:
  leftmain_stenosis_binary: !!float 0.1
  lad_stenosis_binary: !!float 0.1
  mid_lad_stenosis_binary: !!float 0.1
  dist_lad_stenosis_binary: !!float 0.1
  diagonal_stenosis_binary: !!float 0.1
  D2_stenosis_binary: !!float 0.1 # Update head structure for D2 stenosis
  lcx_stenosis_binary: !!float 0.1 # Update head structure for lcx stenosis
  dist_lcx_stenosis_binary: !!float 0.1 # Update head structure for dist lcx stenosis
  om1_stenosis_binary: !!float 0.1 # Update head structure for om1 stenosis
  om2_stenosis_binary: !!float 0.1 # Update head structure for om2 stenosis
  bx_stenosis_binary: !!float 0.1 # Update head structure for bx stenosis
  leftmain_stenosis_binary: !!float 0.1 # Update head structure for leftmain stenosis
  lad_stenosis: !!float 0.1 # Update head structure for lad stenosis
  mid_lad_stenosis: !!float 0.1 # Update head structure for mid lad stenosis
  dist_lad_stenosis: !!float 0.1 # Update head structure for dist lad stenosis
  diagonal_stenosis: !!float 0.1 # Update head structure for diagonal stenosis
  D2_stenosis: !!float 0.1 # Update head structure for D2 stenosis
  lcx_stenosis: !!float 0.1 # Update head structure for lcx stenosis
  dist_lcx_stenosis: !!float 0.1 # Update head structure for dist lcx stenosis
  om1_stenosis: !!float 0.1 # Update head structure for om1 stenosis
  om2_stenosis: !!float 0.1 # Update head structure for om2 stenosis
  bx_stenosis: !!float 0.1 # Update head structure for bx stenosis
  prox_rca_stenosis_binary: !!float 0.1
  mid_rca_stenosis_binary: !!float 0.1
  dist_rca_stenosis_binary: !!float 0.1
  pda_stenosis_binary: !!float 0.1
  posterolateral_stenosis_binary: !!float 0.1
  prox_rca_stenosis: !!float 0.1
  mid_rca_stenosis: !!float 0.1
  dist_rca_stenosis: !!float 0.1
  pda_stenosis: !!float 0.1
  posterolateral_stenosis: !!float 0.1
loss_structure:
  leftmain_stenosis_binary: !!str bce_logit
  lad_stenosis_binary: !!str bce_logit
  mid_lad_stenosis_binary: !!str bce_logit
  dist_lad_stenosis_binary: !!str bce_logit
  diagonal_stenosis_binary: !!str bce_logit
  D2_stenosis_binary: !!str bce_logit
  lcx_stenosis_binary: !!str bce_logit
  dist_lcx_stenosis_binary: !!str bce_logit
  om1_stenosis_binary: !!str bce_logit
  om2_stenosis_binary: !!str bce_logit
  bx_stenosis_binary: !!str bce_logit
  leftmain_stenosis: !!str mae
  lad_stenosis: !!str mae
  mid_lad_stenosis: !!str mae
  dist_lad_stenosis: !!str mae
  diagonal_stenosis: !!str mae
  D2_stenosis: !!str mae
  lcx_stenosis: !!str mae
  dist_lcx_stenosis: !!str mae
  om1_stenosis: !!str mae
  om2_stenosis: !!str mae
  bx_stenosis: !!str mae
  prox_rca_stenosis_binary: !!str bce_logit
  mid_rca_stenosis_binary: !!str bce_logit
  dist_rca_stenosis_binary: !!str bce_logit
  pda_stenosis_binary: !!str bce_logit
  posterolateral_stenosis_binary: !!str bce_logit
  prox_rca_stenosis: !!str mae
  mid_rca_stenosis: !!str mae
  dist_rca_stenosis: !!str mae
  pda_stenosis: !!str mae
  posterolateral_stenosis: !!str mae
head_weights:
  leftmain_stenosis_binary: !!float 1.0 # Vous pouvez ajuster si besoin
  lad_stenosis_binary: !!float 1.0 # Vous pouvez ajuster si besoin
  mid_lad_stenosis_binary: !!float 1.0 # Vous pouvez ajuster si besoin
  dist_lad_stenosis_binary: !!float 1.0 # Vous pouvez ajuster si besoin
  diagonal_stenosis_binary: !!float 1.0 # Vous pouvez ajuster si besoin
  D2_stenosis_binary: !!float 1.0 # Vous pouvez ajuster si besoin     
  lcx_stenosis_binary: !!float 1.0 # Vous pouvez ajuster si besoin
  dist_lcx_stenosis_binary: !!float 1.0 # Vous pouvez ajuster si besoin
  om1_stenosis_binary: !!float 1.0 # Vous pouvez ajuster si besoin
  om2_stenosis_binary: !!float 1.0 # Vous pouvez ajuster si besoin
  bx_stenosis_binary: !!float 1.0 # Vous pouvez ajuster si besoin
  leftmain_stenosis: !!float 1.0 # Vous pouvez ajuster si besoin
  lad_stenosis: !!float 1.0 # Vous pouvez ajuster si besoin
  mid_lad_stenosis: !!float 1.0 # Vous pouvez ajuster si besoin
  dist_lad_stenosis: !!float 1.0 # Vous pouvez ajuster si besoin
  diagonal_stenosis: !!float 1.0 # Vous pouvez ajuster si besoin
  D2_stenosis: !!float 1.0 # Vous pouvez ajuster si besoin
  lcx_stenosis: !!float 1.0 # Vous pouvez ajuster si besoin
  dist_lcx_stenosis: !!float 1.0 # Vous pouvez ajuster si besoin
  om1_stenosis: !!float 1.0 # Vous pouvez ajuster si besoin
  om2_stenosis: !!float 1.0 # Vous pouvez ajuster si besoin
  bx_stenosis: !!float 1.0 # Vous pouvez ajuster si besoin
  prox_rca_stenosis_binary: !!float 1.0
  mid_rca_stenosis_binary: !!float 1.0
  dist_rca_stenosis_binary: !!float 1.0
  pda_stenosis_binary: !!float 1.0
  posterolateral_stenosis_binary: !!float 1.0
  prox_rca_stenosis: !!float 1.0
  mid_rca_stenosis: !!float 1.0
  dist_rca_stenosis: !!float 1.0
  pda_stenosis: !!float 1.0
  posterolateral_stenosis: !!float 1.0
head_lr:
  leftmain_stenosis_binary: !!float 0.00006998050654973559
  lad_stenosis_binary: !!float 0.00006998050654973559
  mid_lad_stenosis_binary: !!float 0.00006998050654973559
  dist_lad_stenosis_binary: !!float 0.00006998050654973559
  diagonal_stenosis_binary: !!float 0.00006998050654973559
  D2_stenosis_binary: !!float 0.00006998050654973559
  lcx_stenosis_binary: !!float 0.00006998050654973559
  dist_lcx_stenosis_binary: !!float 0.00006998050654973559
  om1_stenosis_binary: !!float 0.00006998050654973559
  om2_stenosis_binary: !!float 0.00006998050654973559
  bx_stenosis_binary: !!float 0.00006998050654973559
  leftmain_stenosis: !!float 0.00006998050654973559
  lad_stenosis: !!float 0.00006998050654973559
  mid_lad_stenosis: !!float 0.00006998050654973559
  dist_lad_stenosis: !!float 0.00006998050654973559
  diagonal_stenosis: !!float 0.00006998050654973559
  D2_stenosis: !!float 0.00006998050654973559
  lcx_stenosis: !!float 0.00006998050654973559
  dist_lcx_stenosis: !!float 0.00006998050654973559
  om1_stenosis: !!float 0.00006998050654973559
  om2_stenosis: !!float 0.00006998050654973559
  bx_stenosis: !!float 0.00006998050654973559
  prox_rca_stenosis_binary: !!float 0.00006998050654973559
  mid_rca_stenosis_binary: !!float 0.00006998050654973559
  dist_rca_stenosis_binary: !!float 0.00006998050654973559
  pda_stenosis_binary: !!float 0.00006998050654973559
  posterolateral_stenosis_binary: !!float 0.00006998050654973559
  prox_rca_stenosis: !!float 0.00006998050654973559
  mid_rca_stenosis: !!float 0.00006998050654973559
  dist_rca_stenosis: !!float 0.00006998050654973559
  pda_stenosis: !!float 0.00006998050654973559
  posterolateral_stenosis: !!float 0.00006998050654973559
head_weight_decay:
  leftmain_stenosis_binary: !!float 0.00000387825282805052
  lad_stenosis_binary: !!float 0.00000387825282805052
  mid_lad_stenosis_binary: !!float 0.00000387825282805052
  dist_lad_stenosis_binary: !!float 0.00000387825282805052
  diagonal_stenosis_binary: !!float 0.00000387825282805052
  D2_stenosis_binary: !!float 0.00000387825282805052
  lcx_stenosis_binary: !!float 0.00000387825282805052
  dist_lcx_stenosis_binary: !!float 0.00000387825282805052
  om1_stenosis_binary: !!float 0.00000387825282805052
  om2_stenosis_binary: !!float 0.00000387825282805052
  bx_stenosis_binary: !!float 0.00000387825282805052
  leftmain_stenosis: !!float 0.00000387825282805052
  lad_stenosis: !!float 0.00000387825282805052
  mid_lad_stenosis: !!float 0.00000387825282805052
  dist_lad_stenosis: !!float 0.00000387825282805052
  diagonal_stenosis: !!float 0.00000387825282805052
  D2_stenosis: !!float 0.00000387825282805052
  lcx_stenosis: !!float 0.00000387825282805052
  dist_lcx_stenosis: !!float 0.00000387825282805052
  om1_stenosis: !!float 0.00000387825282805052
  om2_stenosis: !!float 0.00000387825282805052
  bx_stenosis: !!float 0.00000387825282805052
  prox_rca_stenosis_binary: !!float 0.00000387825282805052
  mid_rca_stenosis_binary: !!float 0.00000387825282805052
  dist_rca_stenosis_binary: !!float 0.00000387825282805052
  pda_stenosis_binary: !!float 0.00000387825282805052
  posterolateral_stenosis_binary: !!float 0.00000387825282805052
  prox_rca_stenosis: !!float 0.00000387825282805052
  mid_rca_stenosis: !!float 0.00000387825282805052
  dist_rca_stenosis: !!float 0.00000387825282805052
  pda_stenosis: !!float 0.00000387825282805052
  posterolateral_stenosis: !!float 0.00000387825282805052
head_task:
  leftmain_stenosis_binary: !!str classification
  lad_stenosis_binary: !!str classification
  mid_lad_stenosis_binary: !!str classification
  dist_lad_stenosis_binary: !!str classification
  diagonal_stenosis_binary: !!str classification
  D2_stenosis_binary: !!str classification
  lcx_stenosis_binary: !!str classification
  dist_lcx_stenosis_binary: !!str classification
  om1_stenosis_binary: !!str classification
  om2_stenosis_binary: !!str classification
  bx_stenosis_binary: !!str classification
  leftmain_stenosis: !!str regression
  lad_stenosis: !!str regression
  mid_lad_stenosis: !!str regression
  dist_lad_stenosis: !!str regression
  diagonal_stenosis: !!str regression
  D2_stenosis: !!str regression
  lcx_stenosis: !!str regression
  dist_lcx_stenosis: !!str regression
  om1_stenosis: !!str regression
  om2_stenosis: !!str regression
  bx_stenosis: !!str regression
  prox_rca_stenosis_binary: !!str classification
  mid_rca_stenosis_binary: !!str classification
  dist_rca_stenosis_binary: !!str classification
  pda_stenosis_binary: !!str classification
  posterolateral_stenosis_binary: !!str classification
  prox_rca_stenosis: !!str regression
  mid_rca_stenosis: !!str regression
  dist_rca_stenosis: !!str regression
  pda_stenosis: !!str regression
  posterolateral_stenosis: !!str regression
# # Label mappings - Used for confusion matrix
labels_map:
  leftmain_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1
  lad_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1
  mid_lad_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1
  dist_lad_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1
  diagonal_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1
  D2_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1
  lcx_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1
  dist_lcx_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1
  om1_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1
  om2_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1
  bx_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1
  prox_rca_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1
  mid_rca_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1
  dist_rca_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1
  pda_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1
  posterolateral_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1
