# Training parameters
epochs: 20
batch_size: 32
num_workers: 16
lr: 0.000025
debug: false
temp: 0.07

# Data parameters
data_filename: data/reports/reports_with_splits.csv
root: "."
target_label: Report
datapoint_loc_label: FileName
frames: 16

# Model parameters
model_name: mvit
pretrained: true

# Optimization parameters
optimizer: AdamW
weight_decay: 0.000001
scheduler_type: cosine
lr_step_period: 5
factor: 0.3

# Distributed training
gpu: 2  # Set to GPU index for single GPU training
local_rank: -1

# Logging parameters
project: deepCORO_CLIP
entity: mhi_ai
tag: deepCORO_CLIP

# Additional parameters
output_dir: outputs
seed: 0
use_amp: true
device: cuda
period: 1

# Metrics control
metrics_control:
  optim_thresh: g_mean
  plot_pred_distribution: true
  plot_metrics_moving_thresh: true
  n_bootstrap: 100
  q_bootstrap: 0.05

# Data augmentation
rand_augment: true
resize: 224
apply_mask: false
view_count: null

# Checkpointing
save_best: loss
resume: false
