# Training parameters
epochs: 30
batch_size: 48
num_workers: 24
learning_rate: 0.000025
debug: false
temperature: 0.1

# Data parameters
data_filename: data/reports/reports_sampled_no_conclusion_1000.csv
root: "."
target_label: Report
datapoint_loc_label: FileName
frames: 16
stride: 2
# Model parameters
model_name: mvit
pretrained: true

# Optimization parameters
optimizer: RAdam
weight_decay: 0.000001
scheduler_type: step
lr_step_period: 110
factor: 0.3

# Distributed training
gpu: 0  # Set to GPU index for single GPU training
local_rank: -1

# Logging parameters
project: deepCORO_CLIP
entity: mhi_ai
tag: DeepCORO_Clip_Sweep_Learnable_Temp_40k

# Additional parameters
output_dir: outputs
seed: 0
use_amp: true
device: cuda
period: 1

# Metrics control
metrics_control:
  optimization_threshold: g_mean
  plot_prediction_distribution: true
  plot_metrics_moving_threshold: true
  num_bootstrap: 100
  quantile_bootstrap: 0.05

# Data augmentation
random_augment: false
resize: 224
apply_mask: false
view_count: null

# Checkpointing
save_best: loss
resume: false
