# Training parameters
epochs: !!int 2
batch_size: !!int 16
num_workers: !!int 12
lr: !!float 0.000025
debug: !!bool false
temp: !!float 1

# Data parameters
data_filename: !!str data/reports/reports_with_splits_subset.csv
root: !!str "."
target_label: !!str Report
datapoint_loc_label: !!str FileName
frames: !!int 16
stride: !!int 2

# Model parameters
model_name: !!str mvit
pretrained: !!bool true
log_temp: !!bool true

# Optimization parameters
optimizer: !!str AdamW
weight_decay: !!float 0.000001
scheduler_type: !!str cosine
lr_step_period: !!int 1
factor: !!float 0.3

# Additional parameters
output_dir: !!str outputs
seed: !!int 0
use_amp: !!bool true
device: !!str cuda
period: !!int 1

# Loss parameters
loss_name: !!str contrastive

# Metrics control
metrics_control:
  optim_thresh: !!str g_mean
  plot_pred_distribution: !!bool true
  plot_metrics_moving_thresh: !!bool true
  n_bootstrap: !!int 100
  q_bootstrap: !!float 0.05

# Recall @k
recall_k: [1, 5, 10, 50]

# Data augmentation
rand_augment: !!bool false
resize: !!int 224
apply_mask: !!bool false
view_count: !!null null

# Checkpointing
save_best: !!str loss
resume: !!bool false

# Logging
project: !!str deepcoro_clip
entity: !!str jacques-delfrate
tag: !!str mvit_pretrained
