program: scripts/train_model.py
name: "My_DeepCORO_Clip_Sweep_new_hyperparam"
method: bayes

metric:
  name: "best_val_loss"
  goal: "minimize"

parameters:
  learning_rate:
    distribution: log_uniform_values
    min: 5e-6
    max: 1e-4

  optimizer:
    values: ["AdamW", "RAdam"]

  scheduler_type:
    values: ["step", "cosine"]

  max_num_videos:
    values: [4]

  lr_step_period:
    values: [5, 10, 15]

  factor:
    values: [0.1, 0.3, 0.5]

  epochs:
    values: [20, 30]

  batch_size:
    values: [10]
  
  gpu:
    values: [0]

  num_heads:
    values: [1, 2, 4]

  aggregator_depth:
    values: [1, 2]
  
  temperature:
    distribution: uniform
    min: 0.07
    max: 0.12

  # New hyperparameters:
  dropout:
    distribution: uniform
    min: 0.15
    max: 0.25

  video_freeze_ratio:
    values: [0.5, 0.85, 0.8, 0.9]

  text_freeze_ratio:
    values: [0.8, 0.9, 0.7, 1.0]

  patience:
    values: [3, 5, 8, 10]
    
  stride:
    values: [1, 2, 3]

command:
  - bash
  - /volume/DeepCORO_CLIP/config/runner.sh
  - ${program}
  - "config/default_config.yaml"
  - ${args}