# sweep_config.yaml
command:
  - torchrun
  - "--nproc_per_node=2"
  - "--master_port=29500"
  - "scripts/train_model_multi_gpu.py"
  - ${args}

name: "robert_dataset_subset_10k"
project: "dev_deep_coro_clip"
entity: "jacques-delfrate"

method: bayes

metric:
  name: val/loss
  goal: minimize

parameters:
  learning_rate:
    distribution: log_uniform_values
    min: 1e-6
    max: 1e-4

  optimizer:
    values: ["AdamW", "RAdam"]
  scheduler_type:
    values: ["cosine", "step"]
  lr_step_period:
    values: [1]
  factor:
    values: [0.1, 0.3, 0.5]
  batch_size:
    values: [8, 14, 16]
  temperature:
    min: 0.05
    max: 0.15
    distribution: uniform 
  dropout:
    distribution: uniform
    min: 0.0
    max: 0.5    
  video_freeze_ratio:
    values: [0.0, 0.5, 1.0]    
  text_freeze_ratio:
    values: [0.0, 0.5, 1.0]
  epochs:
    values: [5]
  output_dir:
    values: ["output"]
  num_workers:
    values: [12]
  debug:
    values: [false]
  data_filename:
    values: ["data/reports/robert_dataset_subset_10k.csv"]
  root:
    values: ["."]
  target_label:
    values: ["Report"]
  datapoint_loc_label:
    values: ["FileName"]
  frames:
    values: [16]
  stride:
    values: [2]
  model_name:
    values: ["mvit"]
  multi_video:
    values: [true]
  num_videos:
    values: [5]
  shuffle_videos:
    values: [true]
  groupby_column:
    values: ["StudyInstanceUID"]
  pretrained:
    values: [true]
  weight_decay:
    values: [0.000001]
  seed:
    values: [42]
  use_amp:
    values: [true]
  device:
    values: ["cuda"]
  period:
    values: [1]
  loss_name:
    values: ["contrastive"]
  metrics_control:
    values: ['
      {
        "optim_thresh": "g_mean", 
        "plot_pred_distribution": true, 
        "plot_metrics_moving_thresh": true, 
        "n_bootstrap": 100, 
        "q_bootstrap": 0.05
      }
    ']
  recall_k:
    values: [[1, 5, 10, 50]]
  ndcg_k:
    values: [[5]]
  rand_augment:
    values: [false]
  resize:
    values: [224]
  apply_mask:
    values: [false]
  view_count:
    values: [null]
  save_best:
    values: ["loss"]
  resume_training:
    values: [false]
  checkpoint:
    values: [null]
  tag:
    values: ["mvit_pretrained"]
  name:
    values: ["robert_dataset_subset_10k"]
  project:
    values: ["dev_deep_coro_clip"]
  entity:
    values: ["jacques-delfrate"]

early_terminate:
  type: hyperband
  min_iter: 3
  eta: 2
  s: 2
