program: scripts/train_model.py
name: "My_DeepCORO_Clip_Sweep_new_hyperparam"
method: bayes

metric:
  name: "best_val_loss"
  goal: "minimize"

parameters:
  learning_rate:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-4

  optimizer:
    values: ["AdamW", "RAdam"]

  scheduler_type:
    values: ["step", "cosine"]

  lr_step_period:
    values: [5, 10, 15]

  factor:
    values: [0.1, 0.3, 0.5]

  epochs:
    values: [20, 30, 40]

  batch_size:
    values: [10, 12]

  temperature:
    distribution: uniform
    min: 0.05
    max: 0.15

  random_augment:
    values: [true, false]

  # New hyperparameters:
  dropout:
    distribution: uniform
    min: 0.0
    max: 0.5

  video_freeze_ratio:
    values: [0.0, 0.5, 0.8, 1.0]

  text_freeze_ratio:
    values: [0.0, 0.5, 0.8, 1.0]

  patience:
    values: [3, 5, 8, 10]
    
  stride:
    values: [1, 2, 3]

command:
  - bash
  - /volume/DeepCORO_CLIP/config/runner.sh
  - ${program}
  - "config/default_config.yaml"
  - ${args}