program: scripts/train_model.py
name: "DeepCORO_Clip_Sweep_Learnable_Temp_40k"
method: "bayes"
metric:
  name: "best_val_loss"
  goal: "minimize"
parameters:
  learning_rate:
    min: 1e-4
    max: 1e-3
    distribution: "uniform"
  optimizer:
    values: ["AdamW", "RAdam"]
  scheduler_type:
    values: ["cosine"]
  lr_step_period:
    values: [10]
  factor:
    values: [0.1, 0.3, 0.5]
  epochs:
    values: [10, 20]
  batch_size:
    values: [36, 48, 64]
  temperature:
    min: 0.01
    max: 0.5
    distribution: uniform
  random_augment:
    values: [True, False]
command:
  - bash
  - /volume/DeepCORO_CLIP/config/runner.sh
  - ${program}
  - "config/default_config.yaml"
  - ${args}
