command:
  - torchrun
  - "--nproc_per_node=4"
  - "--master_port=29500"
  - "scripts/train_model_multi_gpu.py"
  - "--base_config"
  - "config/base_config.yaml"
  - ${args}

name: "dev_deep_coro_clip_single_video"
project: "dev_deep_coro_clip_single_video"
entity: "mhi_ai"

method: bayes

metric:
  name: val/loss
  goal: minimize

parameters:
  lr:
    distribution: log_uniform_values
    min: 5e-5
    max: 1e-3

  optimizer:
    values: ["RAdam", "AdamW"]

  scheduler_type:
    values: ["step", "cosine"]

  lr_step_period:
    values: [15, 20, 30]

  factor:
    distribution: uniform
    min: 0.2
    max: 0.5

  dropout:
    distribution: uniform
    min: 0.1
    max: 0.2

  video_freeze_ratio:
    distribution: uniform
    min: 0.8
    max: 0.95

  text_freeze_ratio:
    distribution: uniform
    min: 0.7
    max: 0.95

  num_heads:
    values: [2, 4, 8, 16]

  aggregator_depth:
    values: [1, 2, 3, 4]

  temperature:
    distribution: uniform
    min: 0.05
    max: 0.1

  video_weight_decay:
    distribution: log_uniform_values
    min: 1e-7
    max: 1e-4
  text_weight_decay:
    distribution: log_uniform_values
    min: 1e-7
    max: 1e-6

  batch_size:
    values: [96]
  loss_name:
    values: ["contrastive"]
  tag:
    values: ["mvit_pretrained"]
  name:
    values: ["dev_deep_coro_clip_single_video"]
  project:
    values: ["dev_deep_coro_clip_single_video"]
  entity:
    values: ["mhi_ai"]

early_terminate:
  type: hyperband
  min_iter: 3
  eta: 2
  s: 2
