# sweep_config.yaml
command:
  - torchrun
  - "--nproc_per_node=1"
  - "--master_port=29500"
  - "scripts/train_model_multi_gpu.py"
  - "--base_config"
  - "config/base_config.yaml"
  - ${args}

name: "dev_deep_coro_clip"
project: "dev_deep_coro_clip"
entity: "mhi_ai"

method: bayes

metric:
  name: val/loss
  goal: minimize

parameters:
  lr:
    values: [0.0001]
  optimizer:
    values: ["RAdam"]
  scheduler_type:
    values: ["step"]
  lr_step_period:
    values: [15]
  factor:
    values: [0.3]
  batch_size:
    values: [8]
  num_heads:
    values: [2]
  aggregator_depth:
    values: [2]
  temperature:
    values: [0.07]
  dropout:
    values: [0.2]
  video_freeze_ratio:
    values: [0.8]
  text_freeze_ratio:
    values: [0.5]
  weight_decay:
    values: [0.000001]
  loss_name:
    values: ["contrastive"]
  tag:
    values: ["mvit_pretrained"]
  name:
    values: ["dev_deep_coro_clip"]
  project:
    values: ["dev_deep_coro_clip"]
  entity:
    values: ["mhi_ai"]

early_terminate:
  type: hyperband
  min_iter: 3
  eta: 2
  s: 2
