# sweep_config.yaml
command:
  - torchrun
  - "--nproc_per_node=1"
  - "--master_port=29500"
  - "scripts/train_model_multi_gpu.py"
  - "--base_config"
  - "config/base_config.yaml"
  - ${args}

name: "dev_deep_coro_clip"
project: "dev_deep_coro_clip"
entity: "jacques-delfrate"

method: bayes

metric:
  name: val/loss
  goal: minimize

parameters:
  lr:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-4
  optimizer:
    values: ["AdamW", "RAdam"]
  scheduler_type:
    values: ["cosine", "step"]
  lr_step_period:
    values: [1]
  factor:
    values: [0.1, 0.3, 0.5]
  batch_size:
    values: [10, 12]
  temperature:
    min: 0.05
    max: 0.15
    distribution: uniform 
  dropout:
    distribution: uniform
    min: 0.0
    max: 0.5    
  video_freeze_ratio:
    values: [0.0, 0.5, 0.8, 1.0]
  text_freeze_ratio:
    values: [0.0, 0.5, 1.0]
  weight_decay:
    values: [0.000001]
  loss_name:
    values: ["contrastive"]
  tag:
    values: ["mvit_pretrained"]
  name:
    values: ["dev_deep_coro_clip"]
  project:
    values: ["dev_deep_coro_clip"]
  entity:
    values: ["jacques-delfrate"]

early_terminate:
  type: hyperband
  min_iter: 3
  eta: 2
  s: 2
