pipeline_project: !!str "DeepCORO_clip"
# Training parameters
epochs: !!int 10
num_workers: !!int 48
debug: !!bool false
use_amp: !!bool true
period: !!int 1
device: !!str cuda
run_mode: !!str train
max_grad_norm: !!float 1.0
# Dataset parameters
data_filename: !!str data/reports/report_sampled_200.csv
root: !!str "."
target_label: !!str Report
datapoint_loc_label: !!str FileName
frames: !!int 32
stride: !!int 1
multi_video: !!bool false
num_videos: !!int 4
groupby_column: !!str StudyInstanceUID
shuffle_videos: !!bool true
batch_size: !!int 16
# Seed
seed: !!int 42
# Model parameters
# Available model_name options: mvit, r3d, x3d_s, x3d_m
model_name: !!str x3d_m
pretrained: !!bool true
# Optimizer parameters
optimizer: !!str AdamW
lr: !!float 0.0001078401014773209
scheduler_name: !!str cosine_with_warmup
num_warmup_percent: !!float 0.15
lr_step_period: !!int 5
factor: !!float 0.1
loss_name: !!str siglip_ddp
video_weight_decay: !!float 0.000022030638569939196
text_weight_decay: !!float 0.0000002104425351098601
gradient_accumulation_steps: !!int 2
num_hard_restarts_cycles: !!float 1.0
warm_restart_tmult: !!int 2
# Model architecture parameters
num_heads: !!int 8
aggregator_depth: !!int 2
temperature: !!float 0.07928054730507551
dropout: !!float 0.0993431288332216
video_freeze_ratio: !!float 1.0
text_freeze_ratio: !!float 0.8
# Checkpointing
resume_training: !!bool false
checkpoint: !!str outputs/deepCORO_CLIP/DeepCORO_Clip_Sweep_Learnable_Temp_Full_mvit_b12_f16_RAdam_lr0.0001_20250114-190320_2o5xoevj/checkpoints/latest.pt
output_dir: !!str outputs
save_best: !!str loss
# Metrics
# Recall @k
recall_k: [1, 5, 10, 50]
# NDCG @k
ndcg_k: [5]
# Data augmentation
rand_augment: !!bool true
resize: !!int 224
view_count: !!null null
apply_mask: !!bool false
# wandb parameters
tag: !!str x3d_m_pretrained
name: !!str DeepCORO_Clip_Sweep_Single_Video
project: !!str DeepCORO_Clip_Sweep_Single_Video
entity: !!str mhi_ai
use_wandb: !!bool true
# Inference parameters
inference_results_path: outputs/inference_results
metadata_path: !!null null
text_embeddings_path: !!null null
topk: !!int 5
base_checkpoint_path: outputs/checkpoints
