# Pipeline parameters
pipeline_project: !!str DeepCORO_video_linear_probing
output_dir: !!str outputs
run_mode: !!str train
epochs: !!int 10
seed: !!int 42
# wandb parameters
tag: !!str mvit_pretrained
name: !!str dev_deep_coro_linear_probing
project: !!str dev_deep_coro_linear_probing
entity: !!str mhi_ai
use_wandb: !!bool true
# Training parameters
lr: !!float 0.00004630534905624309
scheduler_name: !!str step
lr_step_period: !!int 2
factor: !!float 0.24040344158856675
optimizer: !!str RAdam
weight_decay: !!float 0.00000025007452242887
use_amp: !!bool true
gradient_accumulation_steps: !!int 1
num_warmup_percent: !!float 0.1
num_hard_restarts_cycles: !!float 1.0
warm_restart_tmult: !!int 2
# Dataset parameters
data_filename: !!str /volume/DeepCORO_CLIP/data3/filtered_deep_rv_data_alpha_updated.csv
num_workers: !!int 8
batch_size: !!int 8
datapoint_loc_label: !!str FileName
target_label: [Outcome]
rand_augment: !!bool true
resize: !!int 224
frames: !!int 16
stride: !!int 1
# Video Encoder parameters
model_name: !!str mvit
aggregator_depth: !!int 2
num_heads: !!int 4
video_freeze_ratio: !!float 0.7257804887551834
dropout: !!float 0.3165126471331081
pretrained: !!bool true
video_encoder_checkpoint_path: !!str /media/data1/jdelfrate/best_epoch_xvwwv5ar.pt
# Linear Probing parameters
task: !!str classification
linear_probing_head: !!str simple_linear_probing
head_structure:
  Outcome: !!int 1
head_dropout:
  Outcome: !!float 0.1
loss_structure:
  Outcome: !!str bce_logit
head_weights:
  Outcome: !!float 1.0
# Label mappings - Used for confusion matrix
labels_map:
  Outcome:
    normal: !!int 0
    abnormal: !!int 1
