# Pipeline parameters
pipeline_project: !!str DeepCORO_video_linear_probing
output_dir: !!str outputs
run_mode: !!str train
epochs: !!int 10
seed: !!int 42
# wandb parameters
tag: !!str mvit_pretrained
name: !!str dev_deep_coro_linear_probing
project: !!str dev_deep_coro_linear_probing
entity: !!str mhi_ai
use_wandb: !!bool true
# Training parameters
lr: !!float 0.0003
scheduler_name: !!str step
lr_step_period: !!int 5
factor: !!float 0.3
optimizer: !!str AdamW
weight_decay: !!float 0.00001
use_amp: !!bool true
gradient_accumulation_steps: !!int 1
num_warmup_percent: !!float 0.1
num_hard_restarts_cycles: !!float 1.0
warm_restart_tmult: !!int 2
# Dataset parameters
data_filename: !!str /volume/DeepCORO_CLIP/mes-scripts/dr_non_rca_regression_binary.csv
num_workers: !!int 12
batch_size: !!int 4
datapoint_loc_label: !!str FileName
target_label: [leftmain_stenosis_binary, lad_stenosis_binary, mid_lad_stenosis_binary, dist_lad_stenosis_binary, diagonal_stenosis_binary, D2_stenosis_binary, lcx_stenosis_binary, dist_lcx_stenosis_binary, om1_stenosis_binary, om2_stenosis_binary, bx_stenosis_binary, lima_or_svg_stenosis_binary]
rand_augment: !!bool true
resize: !!int 224
frames: !!int 16
stride: !!int 1
# Video Encoder parameters
model_name: !!str mvit
aggregator_depth: !!int 2
num_heads: !!int 4
video_freeze_ratio: !!float 0.8
dropout: !!float 0.2
pretrained: !!bool true
video_encoder_checkpoint_path: !!str /media/data1/jdelfrate/best_epoch_xvwwv5ar.pt
# Linear Probing parameters
task: !!str classification
linear_probing_head: !!str simple_linear_probing
head_structure:
  leftmain_stenosis_binary: !!int 1 # Update head structure for leftmain stenosis
  lad_stenosis_binary: !!int 1 # Update head structure for lad stenosis
  mid_lad_stenosis_binary: !!int 1 # Update head structure for mid lad stenosis
  dist_lad_stenosis_binary: !!int 1 # Update head structure for dist lad stenosis
  diagonal_stenosis_binary: !!int 1 # Update head structure for diagonal stenosis
  D2_stenosis_binary: !!int 1 # Update head structure for D2 stenosis
  lcx_stenosis_binary: !!int 1 # Update head structure for lcx stenosis
  dist_lcx_stenosis_binary: !!int 1 # Update head structure for dist lcx stenosis
  om1_stenosis_binary: !!int 1 # Update head structure for om1 stenosis
  om2_stenosis_binary: !!int 1 # Update head structure for om2 stenosis
  bx_stenosis_binary: !!int 1 # Update head structure for bx stenosis
  lima_or_svg_stenosis_binary: !!int 1 # Up
head_dropout:
  leftmain_stenosis_binary: !!float 0.1 # Vous pouvez ajuster si besoin
  lad_stenosis_binary: !!float 0.1 # Vous pouvez ajuster si besoin
  mid_lad_stenosis_binary: !!float 0.1 # Vous pouvez ajuster si besoin
  dist_lad_stenosis_binary: !!float 0.1 # Vous pouvez ajuster si besoin
  diagonal_stenosis_binary: !!float 0.1 # Vous pouvez ajuster si besoin
  D2_stenosis_binary: !!float 0.1 # Vous pouvez ajuster si besoin
  lcx_stenosis_binary: !!float 0.1 # Vous pouvez ajuster si besoin
  dist_lcx_stenosis_binary: !!float 0.1 # Vous pouvez ajuster si besoin
  om1_stenosis_binary: !!float 0.1 # Vous pouvez ajuster si besoin
  om2_stenosis_binary: !!float 0.1 # Vous pouvez ajuster si besoin
  bx_stenosis_binary: !!float 0.1 # Vous pouvez ajuster si besoin
  lima_or_svg_stenosis_binary: !!float 0.1 # Vous pouvez ajuster si besoin
loss_structure:
  leftmain_stenosis_binary: !!str bce_logit # Update loss function for leftmain stenosis
  lad_stenosis_binary: !!str bce_logit # Update loss function for lad stenosis
  mid_lad_stenosis_binary: !!str bce_logit # Update loss function for mid lad stenosis
  dist_lad_stenosis_binary: !!str bce_logit # Update loss function for dist lad stenosis
  diagonal_stenosis_binary: !!str bce_logit # Update loss function for diagonal stenosis
  D2_stenosis_binary: !!str bce_logit # Update loss function for D2 stenosis
  lcx_stenosis_binary: !!str bce_logit # Update loss function for lcx stenosis
  dist_lcx_stenosis_binary: !!str bce_logit # Update loss function for dist lcx stenosis
  om1_stenosis_binary: !!str bce_logit # Update loss function for om1 stenosis
  om2_stenosis_binary: !!str bce_logit # Update loss function for om2 stenosis
  bx_stenosis_binary: !!str bce_logit # Update loss function for bx stenosis
  lima_or_svg_stenosis_binary: !!str bce_logit
head_weights:
  leftmain_stenosis_binary: !!float 1.0
  lad_stenosis_binary: !!float 1.0
  mid_lad_stenosis_binary: !!float 1.0
  dist_lad_stenosis_binary: !!float 1.0
  diagonal_stenosis_binary: !!float 1.0
  D2_stenosis_binary: !!float 1.0
  lcx_stenosis_binary: !!float 1.0
  dist_lcx_stenosis_binary: !!float 1.0
  om1_stenosis_binary: !!float 1.0
  om2_stenosis_binary: !!float 1.0
  bx_stenosis_binary: !!float 1.0
  lima_or_svg_stenosis_binary: !!float 1.0
labels_map:
  leftmain_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1 # Update labels for leftmain stenosis
  lad_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1 # Update labels for lad stenosis
  mid_lad_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1 # Update labels for mid lad stenosis
  dist_lad_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1 # Update labels for dist lad stenosis
  diagonal_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1 # Update labels for diagonal stenosis
  D2_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1 # Update labels for D2 stenosis
  lcx_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1 # Update labels for lcx stenosis
  dist_lcx_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1 # Update labels for dist lcx stenosis
  om1_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1 # 
  om2_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1 # Update labels for om2 stenosis
  bx_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1 # Update labels for bx stenosis
  lima_or_svg_stenosis_binary:
    normal: !!int 0
    abnormal: !!int 1
